### ISSUE TITLE
Support S3/COS

### ISSUE THREAD

**Issue by romeokienzler** [kalbfuss/pyframe#2]
Cloud Object Storage is one of the most reliable, cost efficient, elastic and easy to use storage systems around. 

Would be nice if Python s3fs could be used - I can provide code snippets

**Comment by kalbfuss** [comment]
I am not using S3/COS nor do I have a subscription. Means, I do not have access to a suitable development and test environment. Since this does not sound like a feature I would want to use in the near future, I will leave it to you (or anyone else) to implement. Your starting point will be the *repository.Repository* class. Feel free to provide a pull request afterwards.

**Comment by romeokienzler** [comment]
Thanks @kalbfuss looking into it

**Comment by kalbfuss** [comment]
I have done a bit of reading about [rclone](https://rclone.org), which I did not know before. The number of supported cloud storage providers is impressive. Interestingly, there is a python wrapper called [rclone-python](https://pypi.org/project/rclone-python/), which provides all the required functionality to implement a repository, i.e. essentially listing the content of directories, retrieving file properties and copying/downloading files.
How about implementing an rclone repository class, which would make nearly every common cloud storage provider compatible with pyframe?

**Comment by kalbfuss** [comment]
Since I was very much intrigued by the capabilities of *rclone*, I have done a first implementation of an *rclone* repository. I just pushed the change to github so you can test.
You will have to install the additional package *rclone-python* from [pypi.org](https://pypi.org) for the latest version of pyframe to run.
Remotes need to be configured in rclone first, before they can be used in pyframe. Pyframe does not provide any functionality to setup rclone remotes.
Afterwards, adding an rclone repository to pyframe is as simple as adding the following lines to *config.yaml*:
```
repositories:
  my_rclone_rep:
    type: rclone
    root: <remote>:<root>
```
Since rclone supports WebDAV, I have used it to access and show files from my WebDAV test environment. Worked like a charm.

**Comment by romeokienzler** [comment]
Wow thanks a lot!
